//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package mx.gob.segob.dgti.ecurp.wserv.services;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import mx.gob.segob.dgti.ecurp.wserv.services.xsd.DatosConsultaCurp;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datos" type="{http://services.wserv.ecurp.dgti.segob.gob.mx/xsd}DatosConsultaCurp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datos"
})
@XmlRootElement(name = "consultarPorCurp")
public class ConsultarPorCurp {

    @XmlElementRef(name = "datos", namespace = "http://services.wserv.ecurp.dgti.segob.gob.mx", type = JAXBElement.class)
    protected JAXBElement<DatosConsultaCurp> datos;

    /**
     * Gets the value of the datos property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DatosConsultaCurp }{@code >}
     *     
     */
    public JAXBElement<DatosConsultaCurp> getDatos() {
        return datos;
    }

    /**
     * Sets the value of the datos property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DatosConsultaCurp }{@code >}
     *     
     */
    public void setDatos(JAXBElement<DatosConsultaCurp> value) {
        this.datos = ((JAXBElement<DatosConsultaCurp> ) value);
    }

}
